name: Tests
on:
  workflow_call:

  pull_request:
    paths:
      - 'packages/**'
      - 'tests/**'
      - '**.spec.js'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  e2e:
    strategy:
      matrix:
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      # TODO: Install not all dependencies, but only those required for this workflow
      - name: Install dependencies
        run: npm ci

      - run: npm test
